# Use the official .NET SDK image as the base
FROM mcr.microsoft.com/dotnet/sdk:8.0

# Set the working directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY . .

# Keep the container running by default
CMD ["tail", "-f", "/dev/null"]